# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_poloniexkey_profile_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poloniexkey',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poloniexkey',
            name='secret',
            field=models.CharField(max_length=255),
        ),
    ]
