# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171120_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='base_32',
            field=models.CharField(default='', max_length=63),
        ),
    ]
